baseurl = "https://wimlouw.com/"
languageCode = "en-uk"
title = "wimlouw"
theme = "hugo-lithium"
googleAnalytics = "UA-178880539-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.bib$", "\\.csv$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/wimlouw"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/wimlouw"

[params]
    description = "Occasional posts: tech resources, coding, &c."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo2.jpeg"
    width = 80
    height = 80
    alt = "logo2"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
