---
title: Including citations in a post
author: Wim Louw
date: '2020-04-18'
categories:
  - learning
  - resources
tags:
  - citations
  - productivity
  - tools
  - work
slug: test-citations
bibliography:
  - refs.bib
link-citations: yes
---

# Resources

- [Adding citations to posts - A minimal example website using blogdown](https://blogdown-demo.rbind.io/2017/08/28/adding-citations-to-posts/)
- [Bibliographies and Citations in R Markdown](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citations)
- [GitHub - crsh/citr: RStudio Addin to Insert Markdown Citations](https://github.com/crsh/citr)
- I installed Zotero, and [Better BibTeX for Zotero](http://retorque.re/zotero-better-bibtex/)
- [Primer — An Introduction to CSL — Citation Style Language 1.0.1-dev documentation](http://docs.citationstyles.org/en/1.0.1/primer.html)
- [knitcitations](https://github.com/cboettig/knitcitations)

# Test

* Ok this is a test --- using some random sources I think I used for a paper a few years ago
* I'm using the citr package, Zotero, and the Better BibTeX Zotero add-in

  >*Blah, blah* 
  
  >*Blah blah [see @edwardb.fiskeElusiveEquityEducation2004, pp. 10-15; also @vanderbergResourceShiftsSouth2001 , ch. 3].*
  
  >*Blah blah [@edwardb.fiskeElusiveEquityEducation2004, pp. 5-9, 20-22 and passim].*
  
  >*Blah blah [ @vanderbergResourceShiftsSouth2001; @edwardb.fiskeElusiveEquityEducation2004]*
  
  >*Van der Berg says blah [-@vanderbergResourceShiftsSouth2001].*
  
  >*@vanderbergResourceShiftsSouth2001 says blah.*
  

OK, works!


# References

Ok, also works!

